### ISSUE TITLE
How to use prencrypt

### ISSUE THREAD

**Issue by Himan000** [hongyuefan/prencrypt#1]
Hi @hongyuefan ,
Is this a new implementation of https://github.com/nucypher/goUmbral? 
Thanks.

**Comment by hongyuefan** [comment]
this is base on goUmbral theory, but not compatible with the Python version, because some params are not equal to that.  

> Hi @hongyuefan ,
> Is this a new implementation of https://github.com/nucypher/goUmbral?
> Thanks.

this is base on goUmbral theory, but not compatible with the Python version, because some params are not equal to that.

**Comment by Himan000** [comment]
Hi @hongyuefan ，
It's great. Nucypher team doesn't support Go version of Umbral anymore. And Nucypher team will upgrate some theory of Capsule in pyUmbral to make it stateless. Thanks for your go version Umbral, because I will base on your code to implement PRE.
