### ISSUE TITLE
go get github.com/hongyuefan/prencrypt with error

### ISSUE THREAD

**Issue by Himan000** [hongyuefan/prencrypt#3]
Hi @hongyuefan ,

When I got prencrypt from github, error occur as below snippet.

```
D:\project\go\prencrypt\main>go get github.com/hongyuefan/prencrypt
go: github.com/hongyuefan/prencrypt upgrade => v0.0.0-20200603032523-da863ccc990f
go get: github.com/hongyuefan/prencrypt@v0.0.0-20200603032523-da863ccc990f: parsing go.mod:
        module declares its path as: prencrypt
                but was required as: github.com/hongyuefan/prencrypt
```

It seems that go.mod should add prefix `github.com/hongyuefan` to the `package`.
I have pull one request.

It would be greatly appreciated if you could reply as soon as possible.

**Comment by Himan000** [comment]
https://github.com/hongyuefan/prencrypt/pull/2

**Comment by hongyuefan** [comment]
thanks for your asking, i fixed it. you can try it again.

**Comment by hongyuefan** [comment]
> Hi @hongyuefan ,
> 
> When I got prencrypt from github, error occur as below snippet.
> 
> ```
> D:\project\go\prencrypt\main>go get github.com/hongyuefan/prencrypt
> go: github.com/hongyuefan/prencrypt upgrade => v0.0.0-20200603032523-da863ccc990f
> go get: github.com/hongyuefan/prencrypt@v0.0.0-20200603032523-da863ccc990f: parsing go.mod:
>         module declares its path as: prencrypt
>                 but was required as: github.com/hongyuefan/prencrypt
> ```
> 
> It seems that go.mod should add prefix `github.com/hongyuefan` to the `package`.
> I have pull one request.
> 
> It would be greatly appreciated if you could reply as soon as possible.



> Hi @hongyuefan ,
> 
> When I got prencrypt from github, error occur as below snippet.
> 
> ```
> D:\project\go\prencrypt\main>go get github.com/hongyuefan/prencrypt
> go: github.com/hongyuefan/prencrypt upgrade => v0.0.0-20200603032523-da863ccc990f
> go get: github.com/hongyuefan/prencrypt@v0.0.0-20200603032523-da863ccc990f: parsing go.mod:
>         module declares its path as: prencrypt
>                 but was required as: github.com/hongyuefan/prencrypt
> ```
> 
> It seems that go.mod should add prefix `github.com/hongyuefan` to the `package`.
> I have pull one request.
> 
> It would be greatly appreciated if you could reply as soon as possible.

thanks for your asking, i fixed it. you can try it again.

> Hi @hongyuefan ,
> 
> When I got prencrypt from github, error occur as below snippet.
> 
> ```
> D:\project\go\prencrypt\main>go get github.com/hongyuefan/prencrypt
> go: github.com/hongyuefan/prencrypt upgrade => v0.0.0-20200603032523-da863ccc990f
> go get: github.com/hongyuefan/prencrypt@v0.0.0-20200603032523-da863ccc990f: parsing go.mod:
>         module declares its path as: prencrypt
>                 but was required as: github.com/hongyuefan/prencrypt
> ```
> 
> It seems that go.mod should add prefix `github.com/hongyuefan` to the `package`.
> I have pull one request.
> 
> It would be greatly appreciated if you could reply as soon as possible.

thanks for your asking, i fixed it. you can try it again.

**Comment by hongyuefan** [comment]
thanks for your asking, i fixed it. you can try it again.

**Comment by Himan000** [comment]
Hi @hongyuefan ,

Thanks. It works now. Great!
