### ISSUE TITLE
Kfrags is inconsistent with that Marshal and UnMarshal back

### ISSUE THREAD

**Issue by Himan000** [hongyuefan/prencrypt#4]
Hi @hongyuefan ，

I changed `prencrypt_test.go`， and found Kfrags is inconsistent with that Marshal and UnMarshal back.

```
package prencrypt

import (
	"bytes"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"prencrypt/capsule"
	"prencrypt/cfrag"
	"prencrypt/keys"
	"prencrypt/kfrag"
	"prencrypt/symcrypt"
)

var (
	N = 1
	T = 1
)

func oneceOp() error {

	plainTextAlice := []byte("hello world")

	privAlice, _ := keys.GenerateKey()
	privBob, _ := keys.GenerateKey()

	// alice generate sharekey
	shareKeyAlice, aCapsule, err := Encapsulate(privAlice.PublicKey)
	if err != nil {
		return err
	}

	capsuleBytes := aCapsule.Marshal()

	//fmt.Println(string(shareKeyAlice), len(shareKeyAlice))

	// alice use sharekey symcrypt plainText
	cipherText, err := symcrypt.EncryptAes(shareKeyAlice, plainTextAlice)
	if err != nil {
		return err
	}

	// alice authrize for bob，shamir secret share scheme
	kFrags, err := KfragsGen(privAlice, privBob.PublicKey, N, T)
	if err != nil {
		return err
	}

	kFragBytes := kFrags[0].Marshal()
	aKflag := kfrag.NewKFrag()
	aKflag.Unmarshal(kFragBytes)

	var cFrags []*cfrag.CFrag
	newCapsule := capsule.NewCapsule()
	newCapsule.Unmarshal(capsuleBytes)



	//reencrypt capsule
	cfrg, err := ReEncapsulate(aKflag, aCapsule, nil)
	if err != nil {
		return err
	}

	cFrags = append(cFrags, cfrg)

	//bob use his privatekey decapsule sharekey
	shareKeyBob, err := DecapsulateFrags(privBob, privAlice.PublicKey, cFrags)
	if err != nil {
		return err
	}

	//bob use sharekey decrypt ciphertext
	plainTextBob, err := symcrypt.DecryptAes(shareKeyBob, cipherText)
	if err != nil {
		return err
	}

	//compare plaintext
	if !bytes.Equal(plainTextAlice, plainTextBob) {
		return fmt.Errorf("plainText is not equal")
	}

	return nil
}

func TestBench(t *testing.T) {
	if !assert.NoError(t, oneceOp()) {
		return
	}
}
```

It seems that is a bug. I am checking it. If you know why, please tell me. Thanks.

**Comment by Himan000** [comment]
Hi @hongyuefan ,

In kfrag.go, I changed function `Unmarshal`, length of `kf.Rk` should be 64 instead of 32. I change it as bellow snippet, and finally works. This should be a small bug, please change source code in github. Thanks.

```
func (kf *KFrag) Unmarshal(data []byte) error {
	bnLen := curvebn.NewCurveBN(nil).Len()
	ptLen := point.NewPoint().Len()
	if len(data) < bnLen*3+ptLen*2 {
		return errors.New("kfrag data len error")
	}
	kf.Id = curvebn.NewCurveBN(data[:bnLen])
	kf.Rk = curvebn.NewCurveBN(data[bnLen : bnLen*3])
	kf.Z1 = curvebn.NewCurveBN(data[bnLen*3 : bnLen*4])
	u := point.NewPoint()
	if err := u.Unmarshal(data[bnLen*4 : bnLen*4+ptLen]); err != nil {
		return err
	}
	kf.U = u
	xa := point.NewPoint()
	if err := xa.Unmarshal(data[bnLen*4+ptLen : bnLen*4+ptLen*2]); err != nil {
		return err
	}
	kf.XA = xa
	kf.Z2 = new(big.Int).SetBytes(data[bnLen*4+ptLen*2:])
	return nil
}
```

**Comment by hongyuefan** [comment]
> Hi @hongyuefan ,
> 
> In `kfrag.go`, I changed function `Unmarshal`. Length of `kf.Rk` should be 64 instead of 32. I change it as bellow snippet, and it finally works. This should be a small bug, please change source code in github. Thanks.
> 
> ```
> func (kf *KFrag) Unmarshal(data []byte) error {
> 	bnLen := curvebn.NewCurveBN(nil).Len()
> 	ptLen := point.NewPoint().Len()
> 	if len(data) < bnLen*3+ptLen*2 {
> 		return errors.New("kfrag data len error")
> 	}
> 	kf.Id = curvebn.NewCurveBN(data[:bnLen])
> 	kf.Rk = curvebn.NewCurveBN(data[bnLen : bnLen*3])
> 	kf.Z1 = curvebn.NewCurveBN(data[bnLen*3 : bnLen*4])
> 	u := point.NewPoint()
> 	if err := u.Unmarshal(data[bnLen*4 : bnLen*4+ptLen]); err != nil {
> 		return err
> 	}
> 	kf.U = u
> 	xa := point.NewPoint()
> 	if err := xa.Unmarshal(data[bnLen*4+ptLen : bnLen*4+ptLen*2]); err != nil {
> 		return err
> 	}
> 	kf.XA = xa
> 	kf.Z2 = new(big.Int).SetBytes(data[bnLen*4+ptLen*2:])
> 	return nil
> }
> ```

thanks, i have fixed it.
