### ISSUE TITLE
KfragsGen have no capsule

### ISSUE THREAD

**Issue by Himan000** [hongyuefan/prencrypt#5]
Hi @hongyuefan ,
If there is another ciphertext encrypted by Alice, proxy and Bob can use previous rkA->B to decrypt new ciphertext. This is a issue. There is no this problem in original pyUmbral. Could you fix it? Thanks.

**Comment by Himan000** [comment]
It seems there is no capsule within KfragsGen in original Umbral paper.

**Comment by hongyuefan** [comment]
> Hi @hongyuefan ,
> If there is another ciphertext encrypted by Alice, proxy and Bob can use previous rkA->B to decrypt new ciphertext. This is a issue. There is no this problem in original pyUmbral. Could you fix it? Thanks.

不太明白你的意思，一个capsule对应一个sharekey，重新加密数据如果是重新生成的capsule+sharekey，是不可能被前一个sharekey解密的

**Comment by Himan000** [comment]
Hi @hongyuefan ,
哈！太好了，可以说中文。我重复看了一遍原始论文和pyUmbral源码。发现pyUmbral跟您这边的实现方式有所不一样，你实现的是原始论文前半部分，pyUmbral还实现了后半部分的KEM，即使用ChaCha20Poly1305进行加密。
您的方式是这样的：
1. A、B产生秘钥对；
2. A由pkA产生sharekey和capsule，**注意capsule是在这里产生的**；
3. A用sharekey对明文m进行加密成c；
4. A用skA和pkB产生转换秘钥rk；
5. proxy用rk重加密capsule成cFrags；
6. B用skB、pkA、cFrags恢复sharekey；

**Comment by hongyuefan** [comment]
> Hi @hongyuefan ,
> 哈！太好了，可以说中文。我重复看了一遍原始论文和pyUmbral源码。发现pyUmbral跟您这边的实现方式有所不一样，你实现的是原始论文前半部分，pyUmbral还实现了后半部分的KEM，即使用ChaCha20Poly1305进行加密。
> 您的方式是这样的：
> 
> 1. A、B产生秘钥对；
> 2. A由pkA产生sharekey和capsule，**注意capsule是在这里产生的**；
> 3. A用sharekey对明文m进行加密成c；
> 4. A用skA和pkB产生转换秘钥rk；
> 5. proxy用rk重加密capsule成cFrags；
> 6. B用skB、pkA、cFrags恢复sharekey；

对的，是这个逻辑，KEM属于另一个系统了吧

**Comment by Himan000** [comment]
先等等，我进一步确认一下再回复您。

**Comment by Himan000** [comment]
Hi @hongyuefan ，
很不幸，刚刚重新试了pyUmbral，它也做不到一把rk钥匙只对应一个密文。

**Comment by hongyuefan** [comment]
> Hi @hongyuefan ，
> 很不幸，刚刚重新试了pyUmbral，它也做不到一把rk钥匙只对应一个密文。

pyUmbral的源码我也看过，他也是这个逻辑

**Comment by Himan000** [comment]
怎么做得到一个rk只对应一个密文呢？否则，A的所有密文只要proxy和B合谋就可以全部解密。

**Comment by Himan000** [comment]
![image](https://user-images.githubusercontent.com/12414107/84379170-f271f000-ac17-11ea-9ebd-6bc512dcd251.png)
像这种就能做得到每一把钥匙只对应一个文件。要看看这个Umbral怎么样加入这个w才行。

**Comment by Himan000** [comment]
貌似图片显示不了。《基于身份的代理重加密及其应用研究》

**Comment by hongyuefan** [comment]
> 貌似图片显示不了。《基于身份的代理重加密及其应用研究》

umbral 前提是属于门限密码学，如何保证不合谋是结合shamir共享结合区块链实现的

**Comment by Himan000** [comment]
是的，nucypher是靠区块链的，换句话说是靠自觉的，他们也是有可能合谋的，只要诱惑足够大他们就有理由合谋，而且很容易合谋。如果基于条件的代理重加密，那他们就不可能合谋。

**Comment by Himan000** [comment]
甚至，只要Bob能拿得到加密后的m2_cipher_text_path, m2_capsule_path，Bob不需要proxy或者矿工都可以解密。
```
m2_c_frags_path = re_encryption(a_public_key_path, a_verifying_key_path, m2_capsule_path,
                                    m1_k_frags_path, b_public_key_path, m2_cipher_text_path)
    re_decryption(m2_c_frags_path, m2_cipher_text_path, m2_capsule_path,
                  b_private_key_path, a_public_key_path, b_public_key_path, a_verifying_key_path, bob_data_path)
```

**Comment by Himan000** [comment]
Hi @hongyuefan ,
我已经加了一个条件，从而避免proxy和Bob共谋。
改动如下：
1. 在`ReKeyGen`，将 $f0 =a \cdot d^{-1} mod q$ 改成 $f0 =a \cdot \psi \cdot d^{-1} mod q$.
2. 在`Encapsulate`，将$K = KDF((pk_A)^{r+u})$ 改成 $KDF((pk_A)^{(r+u)\psi})$.
3. 在Decapsulate，将$K = KDF((E \cdot V )^{a})$ 改为 $K = KDF((E \cdot V )^{a\psi})$
代码我晚点pull request.

**Comment by hongyuefan** [comment]
抱歉刚看到，解密的时候需要这个w值吧，当bob解密的时候这个w值怎么传递的

**Comment by Himan000** [comment]
将w加密保存到capsule，这样三个方法都可以用

**Comment by Himan000** [comment]
Bob解密不需要w
